FROM solr:9.7-slim

# Copy custom schema.xml and solrconfig.xml to the appropriate core directory
COPY schema.xml /opt/solr/server/solr/cartpe_core/conf/
COPY solrconfig.xml /opt/solr/server/solr/cartpe_core/conf/