FROM solr:9.3

# Copy custom schema.xml and solrconfig.xml to the appropriate core directory
COPY solr/schema.xml /opt/solr/server/solr/cartpe_core/conf/
COPY solr/solrconfig.xml /opt/solr/server/solr/cartpe_core/conf/