# Generated by Django 4.2 on 2024-01-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_service', '0004_order_method_alter_order_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('CONFIRMED', 'CONFIRMED'), ('SHIPPED', 'SHIPPED'), ('OUT_FOR_DELIVERY', 'OUT_FOR_DELIVERY'), ('DELIVERED', 'DELIVERED'), ('CANCELLED', 'CANCELLED'), ('RETURNED', 'RETURNED'), ('REFUNDED', 'REFUNDED')], default='PENDING', max_length=255),
        ),
    ]
