# Generated by Django 4.2 on 2024-01-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_service', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='method',
            field=models.CharField(choices=[('UPI', 'UPI'), ('Cash On Delivery', 'Cash On Delivery')], default='UPI', max_length=255),
        ),
    ]
