# Generated by Django 4.2 on 2024-01-27 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_service', '0006_alter_order_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pending_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
            preserve_default=False,
        ),
    ]
