# Generated by Django 4.2 on 2024-02-25 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_service', '0021_remove_wishlist_product_wishlist_product_variant'),
        ('shipping_service', '0004_rename_line2_address_area_and_more'),
        ('order_service', '0007_order_pending_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_variant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='order_item', to='product_service.productvariant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='user_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='shipping_service.useraddress'),
        ),
    ]
