# Generated by Django 4.2 on 2024-03-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_service', '0008_remove_orderitem_product_orderitem_product_variant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='pending_amount',
            new_name='amount_due',
        ),
        migrations.AddField(
            model_name='order',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='amount_refundable',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='is_refundable',
            field=models.BooleanField(default=False),
        ),
    ]
