# Generated by Django 4.2.11 on 2024-06-03 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(choices=[('Order Status', 'Order Status'), ('Shipping and Delivery', 'Shipping and Delivery'), ('Returns and Refunds', 'Returns and Refunds'), ('Payment Issues', 'Payment Issues'), ('Account Issues', 'Account Issues'), ('Product Inquiry', 'Product Inquiry'), ('Technical Support', 'Technical Support'), ('Feedback and Suggestions', 'Feedback and Suggestions'), ('Report a Problem', 'Report a Problem'), ('General Inquiry', 'General Inquiry')], max_length=255)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_us', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
