# Generated by Django 4.2.11 on 2024-05-29 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0003_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
    ]
