# Generated by Django 4.2 on 2024-01-31 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping_service', '0003_alter_useraddress_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='line2',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='line1',
            new_name='building',
        ),
    ]
