export const GET_SHIPPING_ADDRESS_LIST_REQUEST = 'GET_SHIPPING_ADDRESS_LIST_REQUEST'
export const GET_SHIPPING_ADDRESS_LIST_SUCCESS = 'GET_SHIPPING_ADDRESS_LIST_SUCCESS'
export const GET_SHIPPING_ADDRESS_LIST_FAIL = 'GET_SHIPPING_ADDRESS_LIST_FAIL'

export const ADD_SHIPPING_ADDRESS_REQUEST = 'ADD_SHIPPING_ADDRESS_REQUEST'
export const ADD_SHIPPING_ADDRESS_SUCCESS = 'ADD_SHIPPING_ADDRESS_SUCCESS'
export const ADD_SHIPPING_ADDRESS_FAIL = 'ADD_SHIPPING_ADDRESS_FAIL'

export const EDIT_SHIPPING_ADDRESS_REQUEST = 'EDIT_SHIPPING_ADDRESS_REQUEST'
export const EDIT_SHIPPING_ADDRESS_SUCCESS = 'EDIT_SHIPPING_ADDRESS_SUCCESS'
export const EDIT_SHIPPING_ADDRESS_FAIL = 'EDIT_SHIPPING_ADDRESS_FAIL'

export const REMOVE_SHIPPING_ADDRESS_REQUEST = 'REMOVE_SHIPPING_ADDRESS_REQUEST'
export const REMOVE_SHIPPING_ADDRESS_SUCCESS = 'REMOVE_SHIPPING_ADDRESS_SUCCESS'
export const REMOVE_SHIPPING_ADDRESS_FAIL = 'REMOVE_SHIPPING_ADDRESS_FAIL'