export const GET_CART_ITEMS_REQUEST = 'GET_CART_ITEMS_REQUEST'
export const GET_CART_ITEMS_SUCCESS = 'GET_CART_ITEMS_SUCCESS'
export const GET_CART_ITEMS_FAIL = 'GET_CART_ITEMS_FAIL'

export const ADD_CART_ITEM_REQUEST = 'ADD_CART_ITEM_REQUEST'
export const ADD_CART_ITEM_SUCCESS = 'ADD_CART_ITEM_SUCCESS'
export const ADD_CART_ITEM_FAIL = 'ADD_CART_ITEM_FAIL'

export const UPDATE_CART_ITEM_REQUEST = 'UPDATE_CART_ITEM_REQUEST'
export const UPDATE_CART_ITEM_SUCCESS = 'UPDATE_CART_ITEM_SUCCESS'
export const UPDATE_CART_ITEM_FAIL = 'UPDATE_CART_ITEM_FAIL'

export const REMOVE_CART_ITEM_REQUEST = 'REMOVE_CART_ITEM_REQUEST'
export const REMOVE_CART_ITEM_SUCCESS = 'REMOVE_CART_ITEM_SUCCESS'
export const REMOVE_CART_ITEM_FAIL = 'REMOVE_CART_ITEM_FAIL'

export const EMPTY_CART_REQUEST = 'EMPTY_CART_REQUEST'
export const EMPTY_CART_SUCCESS = 'EMPTY_CART_SUCCESS'
export const EMPTY_CART_FAIL = 'EMPTY_CART_FAIL'