# Generated by Django 4.2 on 2023-04-25 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='discount_id',
            new_name='discount',
        ),
    ]
