# Generated by Django 4.2 on 2023-04-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_service', '0006_alter_product_discount_delete_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
