# Generated by Django 4.2 on 2023-05-11 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_service', '0009_alter_product_attribute_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='attribute_value',
            new_name='attribute',
        ),
    ]
