# Generated by Django 4.2 on 2023-05-12 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_service', '0011_alter_attributevalue_attribute'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='attribute',
            new_name='attributes',
        ),
    ]
