# Generated by Django 4.2 on 2024-02-06 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_service', '0015_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='is_wishlisted',
        ),
    ]
