# Generated by Django 4.2 on 2024-02-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_service', '0017_productvariant_productvariantpropertyvalue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='properties',
            field=models.ManyToManyField(blank=True, related_name='product_variants', to='product_service.productvariantpropertyvalue'),
        ),
    ]
