# Generated by Django 5.0.7 on 2024-09-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_service", "0023_alter_productreview_product_alter_productreview_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="image",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
