# Generated by Django 4.2 on 2024-01-24 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order_service', '0006_alter_order_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_mrp', models.DecimalField(decimal_places=2, max_digits=7)),
                ('total_discount_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('total_selling_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('convenience_fee', models.PositiveSmallIntegerField()),
                ('shipping_fee', models.PositiveSmallIntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('round_off_price', models.IntegerField()),
                ('savings_amount', models.IntegerField()),
                ('savings_percent', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='order_service.order')),
            ],
        ),
    ]
